print.factoptd<-function(x,...)
{
cat("\n       -----------------------------    \n")
cat("Title: Factorial ",x$Optcrit,"-optimal  design ","  Date: ", format(Sys.time(), "%a %b %d %Y %H:%M:%S"),"\n",sep="")
cat("       -----------------------------      \n")
cat("\n")
cat("Call:\n")
print(x$call)
cat("\n")
cat("\nNumber of arrays:", x$b, "\n")
cat("\n")
cat("\nDesign vectors:\n")
cat("\n")
print(data.frame(x$desvect))
cat("\n")
cat("\nNumber of resultant ",paste(x$Optcrit,"-optimal factorial design(s):",sep=""), x$tnfd, "\n")
cat("\n")
cat("\nResultant ",x$Optcrit,"-optimal factorial design(s) are:\n",sep="")
cat("\n")
print(data.frame(x$optfctd))
cat("\n", x$Optcrit, "-score value: ", x$optscv,"\n",sep="" )
cat("\n-------------------------------------    \n")
cat("*dpnti: The ith design point  \n")
cat("*fdpnti: Frequency of the ith design point  \n")
cat("*Optfdi: The ith resultant optimal factorial  design \n")
cat("\n")
}
